export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_MOVIES = "GET_MOVIES";
export const ADD_MOVIE = "ADD_MOVIE";
export const DELETE_MOVIE = "DELETE_MOVIE";
export const SET_CURRENT_MOVIE = "SET_CURRENT_MOVIE";
export const CLEAR_CURRENT_MOVIE = "CLEAR_CURRENT_MOVIE";
export const UPDATE_MOVIE = "UPDATE_MOVIE";
export const CLEAR_MOVIES = "CLEAR_MOVIES";
